splash = false

wallpaper {
    monitor = DP-1
    path = ~/Pictures/Wallpapers/Minimalist_Wallpaper_1_1.png
    fit_mode = contain
}

wallpaper {
    monitor = DP-3
    path = ~/Pictures/Wallpapers/Minimalist_Wallpaper_1_2.png
    fit_mode = contain
}
