require("autostart")
require("bindings")
require("decorations")
require("env")
require("input")
require("layout")
require("misc")
require("monitors")
require("rules")
require("workspaces")

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
hl.config({ cursor = { no_hardware_cursors = true } })
